-- ============================================================
--  KAVASI – Supabase PostgreSQL Schema
--  Run this ONCE in the Supabase SQL Editor
--  (Project → SQL Editor → New Query → paste → Run)
-- ============================================================

-- Enable the pgcrypto extension (used for bcrypt-compatible hashing)
-- (bcrypt itself is handled by the app, not the DB)

-- ─────────────────────────────────────────────────────────────
--  ADMINS
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Admins" (
  id          BIGSERIAL PRIMARY KEY,
  email       TEXT NOT NULL UNIQUE,
  password    TEXT NOT NULL,
  name        TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────
--  CONTACTS
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Contacts" (
  id           BIGSERIAL PRIMARY KEY,
  name         TEXT NOT NULL,
  email        TEXT NOT NULL,
  "projectType" TEXT NOT NULL,
  message      TEXT NOT NULL,
  status       TEXT NOT NULL DEFAULT 'unread'
                CHECK (status IN ('unread','read','replied')),
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────
--  PROJECTS
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Projects" (
  id           BIGSERIAL PRIMARY KEY,
  name         TEXT NOT NULL,
  description  TEXT NOT NULL,
  "imageUrl"   TEXT NOT NULL,
  "projectLink" TEXT DEFAULT '',
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────
--  TEAM MEMBERS
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "TeamMembers" (
  id             BIGSERIAL PRIMARY KEY,
  name           TEXT NOT NULL,
  role           TEXT NOT NULL,
  "imageUrl"     TEXT NOT NULL,
  display_order  INT DEFAULT 0,
  created_at     TIMESTAMPTZ DEFAULT NOW(),
  updated_at     TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────
--  JOBS
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Jobs" (
  id          BIGSERIAL PRIMARY KEY,
  title       TEXT NOT NULL,
  type        TEXT NOT NULL
               CHECK (type IN ('Full-Time','Part-Time','Internship','Contract')),
  description TEXT NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────
--  APPLICANTS – application_id is auto-generated by a sequence
-- ─────────────────────────────────────────────────────────────

-- Sequence that starts at 1 and increments by 1
CREATE SEQUENCE IF NOT EXISTS applicant_seq START 1 INCREMENT 1;

CREATE TABLE IF NOT EXISTS "Applicants" (
  id             BIGSERIAL PRIMARY KEY,
  -- Auto-formatted: KAVASI-000001, KAVASI-000002, …
  application_id TEXT NOT NULL UNIQUE
                  DEFAULT 'KAVASI-' || LPAD(nextval('applicant_seq')::TEXT, 6, '0'),
  job_id         BIGINT NOT NULL REFERENCES "Jobs"(id) ON DELETE CASCADE,
  name           TEXT NOT NULL,
  email          TEXT NOT NULL,
  mobile         TEXT,
  portfolio      TEXT DEFAULT '',
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────
--  SEED DATA  (same as old database.sql)
-- ─────────────────────────────────────────────────────────────

-- Admin  (password: ewqasdcxz – bcrypt hash)
INSERT INTO "Admins" (email, password, name)
VALUES ('admin@kavasi.com', '$2b$10$GCfJiHGLime5JjLJ6uNV7OOl04rPUN8V0ZAiafFuPyXBXbXbDSlNS', 'Mock Admin')
ON CONFLICT (email) DO NOTHING;

-- Projects
INSERT INTO "Projects" (name, description, "imageUrl", "projectLink") VALUES
('AeroSpace ERP UI',
 'A massive internal enterprise resource planning system redesign for an aerospace company. Built in Next.js and Tailwind.',
 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
 'https://example.com'),
('AutoCRM AI',
 'An automated CRM that leverages local LLMs to categorize and reply to thousands of customer emails automatically.',
 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
 'https://example.com'),
('Fintech Dashboard',
 'High performance data visualization dashboard tracking crypto and fiat assets in real time.',
 'https://images.unsplash.com/photo-1555421689-491a97ff2040?auto=format&fit=crop&q=80&w=800',
 'https://example.com')
ON CONFLICT DO NOTHING;

-- Team Members
INSERT INTO "TeamMembers" (name, role, "imageUrl", display_order) VALUES
('Siddhartha', 'Founder & CEO', '/images/founder.jpg', 1),
('Kashish', 'Lead Developer', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400', 2),
('Rahul Singh', 'AI Specialist', 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&q=80&w=400', 3),
('Rohit Singh', 'UI/UX Designer', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400', 4)
ON CONFLICT DO NOTHING;

-- Jobs
INSERT INTO "Jobs" (id, title, type, description) VALUES
(1, 'Senior Next.js Developer', 'Full-Time', 'Join our team to build high-performance web applications using Next.js 15, Turbopack, and TailwindCSS.'),
(2, 'AI Automation Intern', 'Internship', 'Learn and deploy intelligent workflows using LangChain, OpenAI APIs, and custom Python backend systems.')
ON CONFLICT DO NOTHING;

-- Applicants (application_id auto-assigned by sequence default)
INSERT INTO "Applicants" (job_id, name, email, mobile, portfolio) VALUES
(1, 'Alex Johnson', 'alex@example.com', '9876543210', 'https://github.com/alex'),
(2, 'Maria Garcia', 'maria@example.com', '9876543211', 'https://maria.dev')
ON CONFLICT DO NOTHING;
